from .widget import Widget
from napari_yeasts_granularity import FindCellsOperator
from napari_yeasts_granularity.bridge import NapariBridge
from autooptions import Options
from napari.utils.notifications import show_info, show_warning


class SegmentNucleiWidget(Widget):

    opt_input = "Input"
    opt_sigma = "Gaussian σ"
    opt_log_factor = "Log factor"
    opt_kill_borders = "Kill borders?"
    opt_min_obj_size = "Min object size (voxels)"
    opt_obj_diam = "Diameter (µm)"

    def __init__(self, viewer: "napari.viewer.Viewer"):  # type: ignore
        super().__init__(viewer)

    def getOptions(self):
        options = Options("NapariYeastsGranularity", "SegmentNucleiWidget")
        options.addImage(self.opt_input)
        options.addFloat(
            self.opt_sigma, 
            value=FindCellsOperator.default_gaussian_sigma()
        )
        options.addFloat(
            self.opt_log_factor, 
            value=FindCellsOperator.default_log_factor(), 
            optional=(True, True)
        )
        options.addBool(
            self.opt_kill_borders, 
            value=FindCellsOperator.default_kill_borders()
        )
        options.addInt(
            self.opt_min_obj_size, 
            value=FindCellsOperator.default_min_obj_size()
        )
        options.addFloat(
            self.opt_obj_diam, 
            value=FindCellsOperator.default_objects_diam()
        )
        options.load()
        return options

    def create_operator(self):
        input_layer_name = self.options.value(self.opt_input)
        sigma = self.options.value(self.opt_sigma)
        log_factor = self.options.value(self.opt_log_factor)
        kill_borders = self.options.value(self.opt_kill_borders)
        min_obj_size = self.options.value(self.opt_min_obj_size)
        obj_diam = self.options.value(self.opt_obj_diam)

        input_image = None
        scale = None
        try:
            input_image, scale = NapariBridge.get_image_as_xarray(
                self.viewer, 
                input_layer_name
            )
        except Exception as e:
            show_warning(f"Error retrieving input image: {e}")
            return None

        op = FindCellsOperator()
        op.set_input_image_xarray(input_image)
        op.set_calibration(tuple(scale))
        if log_factor is not None:
            op.set_use_log(True)
            op.set_log_factor(log_factor)
        else:
            op.set_use_log(False)
        op.set_gaussian_sigma(sigma)
        op.set_kill_borders(kill_borders)
        op.set_min_obj_size(min_obj_size)
        op.set_objects_diam(obj_diam)

        return op

    def displayResult(self):
        if self.operator is None:
            show_warning("No operator available to display results.")
            return

        labels = self.operator.get_output_nuclei()
        if labels is None:
            show_warning("No labels generated by the operator.")
            return

        image_layer_name = self.options.value(self.opt_input)
        labels_layer_name = f"{image_layer_name}_nuclei"

        if labels_layer_name in self.viewer.layers:
            l = self.viewer.layers[labels_layer_name]
            self.viewer.layers.remove(l)

        NapariBridge.xarray_to_labels_layer(
            self.viewer,
            labels,
            labels_layer_name
        )
